services:
  lso-client:
    image: lso-client
    network_mode: "host"
    depends_on:
      - lso-server
#      - furhat-sdk
    build:
      context: LSO-client
    secrets:
      - openai-api-key
    environment:
      - OPENAI_API_KEY=/run/secrets/openai-api-key

  lso-server:
    image: lso-server
    network_mode: "host"
    ports:
      - 9999:9999
    build:
      context: LSO-server

# Per containerizzare l'SDK di Furhat, Ã¨ necessario rendere visibile il microfono nel container

#  furhat-sdk:
#    image: furhat-sdk
#    network_mode: "host"
#    ports:
#      - 1932:1932
#      - 8888:8888
#      - 8080:8080
#    build:
#      context: Furhat-SDK

secrets:
  openai-api-key:
    file: ./openai-api-key.txt
